version: '2'
services:
  app:
    build: ../../../simple-logging-app/
    volumes: 
      - /logs/

  elasticsearch:
    image:  docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  fluentd:
    image: fluentd-elastic
    build: ../
    volumes:
      - ./fluent-1.conf:/fluentd/etc/fluent.conf
    volumes_from:
      - app
    links:
      - "elasticsearch"

